### DISCUSSION TITLE
Dynamic generation of grid of cells ?

### DISCUSSION THREAD

**Discussion by loloof64** [slint-ui/slint#1582] [Q&A] [answered]
As an attempt to generate a grid of cells, I've tried the following :
```rust
for index in 64: Rectangle {
    background: mod(mod(index, 8) + (index / 8), 2) == 0 ? #FFDEAD : #CD853F;
    width: size * 0.111px;
    height: size * 0.111px;
}
```
But it seems I'm missing a way to position all those cells. Furthermore, I'm using a single loop, where two nested loops would help much more.

So is it possible to do this ?

**Comment by ogoffart** [comment, marked as answer]
You can use the  `x` and `y` properties to position elements that are not in a layout.

Example:

```css  
   for index in 64: Rectangle {
        background: mod(mod(index, 8) + (index / 8), 2) == 0 ? #FFDEAD : #CD853F;
        width: size * 0.111px;
        height: size * 0.111px;
        x: width * mod(index, 8);
        y: height * floor(index/8);
    }
```

[demo](https://slint-ui.com/releases/0.2.5/editor/?snippet=%0Aexport+Demo+%3A%3D+Window+%7B%0A++++property+%3Cint%3E+size+%3A+300%3B%0A++++for+index+in+64%3A+Rectangle+%7B%0A++++++++background%3A+mod%28mod%28index%2C+8%29+%2B+%28index+%2F+8%29%2C+2%29+%3D%3D+0+%3F+%23FFDEAD+%3A+%23CD853F%3B%0A++++++++width%3A+size+*+0.111px%3B%0A++++++++height%3A+size+*+0.111px%3B%0A++++++++x%3A+width+*+mod%28index%2C+8%29%3B%0A++++++++y%3A+height+*+floor%28index%2F8%29%3B%0A++++%7D%0A%7D%0A)
