### DISCUSSION TITLE
Is the builder pattern or similar possible?

### DISCUSSION THREAD

**Discussion by spikespaz** [slint-ui/slint#3942] [General]
I am making custom widgets and have multiple supported styles. A button can have the following styling:

```yaml
export struct ButtonStyle {
  border-width: length,
  border-radius: length,
  filled: bool,
  font-family: string,
  font-size: length,
  font-weight: int,
  accent-text: bool,
  margin-x: length,
  margin-y: length,
  padding-x: length,
  padding-y: length,
  depress: length,
  shadow-blur: length,
}

export struct AccentScheme {
  fg0: brush,
  fg1: brush,
  fg2: brush,
  fg3: brush,
  fg4: brush,
  bg0: brush,
  bg1: brush,
  bg2: brush,
  bg3: brush,
  bg4: brush,
  light: brush,
  saturated: brush,
  vibrant: brush,
  rich: brush,
}
```

`Button` takes these as properties:

```yaml
export component Button {
  in property <AccentScheme> base-accent: MaterialScheme.base-accent;
  in property <AccentScheme> accent: MaterialScheme.teal;
  in property <ButtonStyle> style: GlobalStyle.button-normal;
```

Now, I may wish to provide several styles for `Button`. I can export these as more components that are named, such as `ButtonLarge`, `Button`, `ButtonSmall`, `ButtonLargeFilled`, `ButtonFilled`, `ButtomSmallFilled`, etc. I would rather not. So I have come up with the following solution:

```yaml
export enum ControlSize {
  Large, Normal, Small
}

export enum ControlTheme {
  Rounded, Boxy
}

export component Button {
  in property <AccentScheme> base-accent: MaterialScheme.base-accent;
  in property <AccentScheme> accent: MaterialScheme.teal;

  in property <bool> filled: false;

  in property <ControlSize> size: ControlSize.Normal;
  in property <ControlTheme> theme: ControlTheme.Rounded;

  in property <ButtonStyle> style: StyleFactory.button(filled, size, theme);
```

Now, I have to make the `StyleFactory` and the `button` function:

```yaml
export global StyleFactory {
  private property <ButtonStyle> button-style: {
    border-width: length,
    border-radius: length,
    filled: bool,
    font-family: string,
    font-size: length,
    font-weight: int,
    accent-text: bool,
    margin-x: length,
    margin-y: length,
    padding-x: length,
    padding-y: length,
    depress: length,
    shadow-blur: length,
  };

  public function button(filled: bool, size: ControlSize, theme: ControlTheme) -> ButtonStyle {
    if (filled) {
      button-style.filled: true;
    }
    if (size == ControlSize.L) {
      button-style.font-size: 12px;
      button-style.font-weight: 600;
      button-style.border-width: 3px;
      button-style.border-radius: 7px;
      button-style.margin-x: 8px;
      button-style.margin-y: 8px;
      button-style.padding-x: 18px;
      button-style.padding-y: 10px;
      button-style.depress: 8px;
      button-style.shadow-blur: 4px;
    } else if (size == ControlSize.M) {
      font-size: 16px;
      font-weight: 500;
      border-width: 2px;
      border-radius: 5px;
      margin-x: 4px;
      margin-y: 4px;
      padding-x: 14px;
      padding-y: 6px;
      depress: 4px;
      shadow-blur: 2px;
    }
    button-style // attempted expression return
  }
}
```

It's not finished, because I don't know how to finish it, but you get the idea. How can I "build" the `ButtonStyle` struct from the arguments to `StyleFactory.button`? I was trying to use a `private property` as state, but can't. I don't see a way to make temporary variables either.
