### DISCUSSION TITLE
fontdue::FontSettings { collection_index: font_index, scale: 40. },    |                       ^^^^^^^^^^^^^^^^^^^^^ missing `load_substitutions` when first building

### DISCUSSION THREAD

**Discussion by LordVagous** [slint-ui/slint#4011] [Q&A] [answered]
Just building it gives you an error, here's my code:
main.rs:
```rust
slint::slint!{
    export component App inherits Window {
        Text {
            text: "hello world";
            color: green;
        }
    }
}
slint::include_modules!();
fn main() {
    App::new().unwrap().run().unwrap()
}
```
build.rs:
```rust
fn main() {
    slint_build::compile("ui/Art.slint").unwrap();
}
```
Cargo.toml:
```toml
[package]
name = "Art"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmt = "0.1.0"
slint = "1.3.0"
[build-dependencies]
slint-build = "1.3.0"
[profile.release]
lto = true
codegen-units = 1
opt-level = 3
```
