### ISSUE TITLE
Nested Flickables don't work

### ISSUE THREAD

**Issue by MattMoszczynski** [slint-ui/slint#1349]
I experienced an issue that if we create a nested Flickable (one Flickable inside another), the inner Flickable won't scroll. My current implementation of the code: https://github.com/Project-Trains/launcher/blob/master/src/ui/market.slint. 

Here's a simplified example:
```css
Item := Rectangle {
    vertical-stretch: 1;
    width: 300phx;

    Rectangle { 
        height: parent.height;
        width: parent.width - 20phx;
        border-radius: 20phx;
        background: #161a1f;
        drop-shadow-color: #0000006e;
        drop-shadow-blur: 12phx;
        clip: true;

        Image {
            source: @image-url("../assets/devlog.jpg");
            image-fit: cover;
            height: parent.height;
            width: parent.width;
        }
    }
}

Test := Rectangle {
    vertical-stretch: 1;
    horizontal-stretch: 1;
    clip: true;

    Flickable {
        interactive: false;
        
        VerticalLayout {                

            Flickable {
                interactive: false;
                height: 180phx;

                HorizontalLayout {
                    clip: true;

                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                }
            }
        }
    }
}

```
