### ISSUE TITLE
Error when using icons

### ISSUE THREAD

**Issue by qw0rd** [slint-ui/slint#1404]
When i use a favicon, it logs this message in the console.
```
Error decoding image: The image format Ico is not supported
```

Code
```
app := Window {
    title: "Some App";
    icon: @image-url("../icons/favicon.ico");
}
```

**Comment by ogoffart** [comment]
The support for `ico` is not enabled by default.
But we use the `image` crate for decoding and it has a `ico` feature.

To enable the feature, add that to your Cargo.toml

```toml
[dependencies]
image = { version = "0.24.0", default-features = false, features = [ "ico" ] }
```
