### ISSUE TITLE
Add tree-sitter-slint for helix And get Error

### ISSUE THREAD

**Issue by erasin** [slint-ui/slint#2519]
I want add tree-sitter-slint for [helix editor](https://github.com/helix-editor/helix).
Add config to `.config/helix/languages.toml`

```toml
[[grammar]]
name = "slint"
source = { git = "https://github.com/slint-ui/slint", rev = "671d22d762fd1031c554251bf8b3c917eab4c311", subpath="editors/tree-sitter-slint" }
```

and run `hx -g fetch && hx -g build` I get Error 

```
❯ hx -g fetch && hx -g build
Fetching 145 grammars
144 up to date git grammars
1 updated grammars
        slint now on 671d22d762fd1031c554251bf8b3c917eab4c311
Building 146 grammars
145 grammars already built
1 grammars failed to build
        Failure 0/1: Failed to execute C/C++ compiler
```
