### ISSUE TITLE
The Button doesn't respects the `horizontal-stretch` property

### ISSUE THREAD

**Issue by ricvelozo** [slint-ui/slint#3037]
The Button doesn't respects the `horizontal-stretch` property when there is a bigger sibling, like that Label:

```slint
import { Button, HorizontalBox, VerticalBox } from "std-widgets.slint";

export global App {
    pure callback quit();
}

export component Counter inherits Window {
    title: "Contador";
    out property <int> count: 5;
    states [
        counting when count > 1: { label.text: "Encerra em \{count} cliques."; }
        ending when count == 1: { label.text: "Encerra no próximo clique!"; }
    ]

    HorizontalBox {
        alignment: center; // Same as `stretch` in this case
        VerticalBox {
            alignment: center;
            label := Text { font-size: 18px; }
            Button {
                horizontal-stretch: 0; // Shouldn't stretch, but does
                text: "Fechar";
                primary: true;
                clicked => {
                    root.count -= 1;
                    if (root.count == 0) {
                        App.quit();
                    }
                }
            }
        }
    }
}
```

Using Fedora 38, GNOME 44/X11. The `Cargo.toml`:

```toml
[dependencies.slint]
version = "1.1"
default-features = false
features = ["compat-1-0", "std", "backend-winit", "renderer-winit-femtovg"]

[build-dependencies]
slint-build = "1.1"
```
