### ISSUE TITLE
LineEdit mask characters hidden when using software renderer

### ISSUE THREAD

**Issue by kivimango** [slint-ui/slint#3057]
Platform:
Manjaro Linux KDE and Redox OS

Steps to reproduce:

Run the following code snippet with

```
SLINT_BACKEND=winit-software cargo run
```

```rust
// Minimal, Reproducible Example 
slint::slint! {
    import { LineEdit, HorizontalBox, VerticalBox} from "std-widgets.slint";
export component Example {
    width: 640px;
    height: 320px;

    HorizontalBox {
        VerticalBox {
            LineEdit {
            height: 32px;
            input-type: password;
            }
        }   
    }
}
}

fn main() {
    Example::new().unwrap().run().unwrap();
}
```

My Cargo.toml:
```toml
[package]
name = "textinput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = { git = "https://github.com/slint-ui/slint", default-features = false, features = ["compat-1-0", "backend-winit", "renderer-winit-software"] }

[build-dependencies]
slint-build = { git = "https://github.com/slint-ui/slint" }
```

Expected behavior:
The LineEdit should display masked characters regardless of backends used.
