### ISSUE TITLE
Panic when pressing End key in LineEdit using software renderer

### ISSUE THREAD

**Issue by kivimango** [slint-ui/slint#3058]
## Platform:
Manjaro Linux KDE, Redox OS

## Steps to reproduce:
Run the following code snippet with

```
SLINT_BACKEND=winit-software cargo run
```

and type something into the LineEdit.
Press the End key.
The app panic with the 
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.22.9/src/point.rs:429:25
```
error message.

```rust
// Minimal, Reproducible Example 
slint::slint! {
    import { LineEdit, HorizontalBox, VerticalBox} from "std-widgets.slint";
    export component Example {
        width: 640px;
        height: 320px;

        HorizontalBox {
            VerticalBox {
                LineEdit {
                height: 32px;
                input-type: text;
                }
            }   
        }
    }
}

fn main() {
    Example::new().unwrap().run().unwrap();
}
```

My Cargo.toml:

```toml
[package]
name = "textinput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = { git = "https://github.com/slint-ui/slint", default-features = false, features = ["compat-1-0", "backend-winit", "renderer-winit-software"] }

[build-dependencies]
slint-build = { git = "https://github.com/slint-ui/slint" }
```

## Expected behavior:
The LineEdit should not panic and the cursor should be moved to the end of the LineEdit's input string.
