### ISSUE TITLE
Slint Rust winit-skia image does not change more than 3 times

### ISSUE THREAD

**Issue by microhobby** [slint-ui/slint#3510]
I have the following rust code:

```rust
use slint::Image;
use std::path::Path;

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let mut turned = false;
    let ui = AppWindow::new()?;

    let ui_handle = ui.as_weak();
    ui.on_request_increase_value(move || {
        let ui = ui_handle.unwrap();
        ui.set_counter(ui.get_counter() + 1);

        if turned {
            turned = false;
            ui.set_led(Image::load_from_path(
                Path::new("./ui/img/led-red-off.png")
            ).unwrap());
        } else {
            turned = true;
            ui.set_led(Image::load_from_path(
                Path::new("./ui/img/led-red-on.png")
            ).unwrap());
        }
    });

    println!("Hello Torizon!");

    ui.run()
}

```

And the .slint:

```css
import { Button, HorizontalBox, VerticalBox, AboutSlint } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    in-out property<image> led: @image-url("img/led-red-off.png");
    callback request-increase-value();

    VerticalBox {
        VerticalLayout {
            alignment: center;
            Image {
                source: led;
            }
        }
        Text {
            horizontal-alignment: center;
            text: "Counter: \{root.counter}";
        }
        HorizontalBox {
            alignment: center;
            Button {
                text: "Increase value";
                clicked => {
                    root.request-increase-value();
                }
            }
        }
     }
}

```

When clicking on the button it will change the image only 3 times when using the winit-skia backend:

https://github.com/slint-ui/slint/assets/2633321/1a8d716a-bdf8-4caa-87b7-65a69ae312aa

The weird behavior is not reproducible when using qt backend:

https://github.com/slint-ui/slint/assets/2633321/1c5d972d-1638-44f1-b87b-81b155f67d60

Let me know if more info is needed or if I'm doing something wrong.

**Comment by microhobby** [comment]
I find out a workaround:

```css
import { Button, HorizontalBox, VerticalBox, AboutSlint } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    in-out property<image> ledOn: @image-url("img/led-red-on.png");
    in-out property<image> ledOff: @image-url("img/led-red-off.png");
    in-out property<image> led: @image-url("img/led-red-off.png");
    in-out property<bool> turned: false;
    callback request-increase-value();

    VerticalBox {
        VerticalLayout {
            alignment: center;
            Image {
                source: led;
            }
        }
        Text {
            horizontal-alignment: center;
            text: "Counter: \{root.counter}";
        }
        HorizontalBox {
            alignment: center;
            Button {
                text: "Increase value";
                clicked => {
                    root.request-increase-value();

                    if (root.turned) {
                        root.led = root.ledOff;
                    } else {
                        root.led = root.ledOn;
                    }
                }
            }
        }
    }
}

```

So, maybe loading it from path every time is not a good practice...
