### ISSUE TITLE
App randomly uses preferred-width

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#3847]
Slint 1.3.0 master branch

Steps to reproduce(not able to create smaller project yet ) - https://github.com/qarmin/czkawka/tree/84b714555099e1451f7f81af6adc7ad0b5198e02
```
git clone https://github.com/qarmin/czkawka.git
cd czkawka
git checkout 84b714555099e1451f7f81af6adc7ad0b5198e02
cargo run # Multiple times
```

This may be a thread synchronization problem or maybe using hashmaps which have unstable sorting

Video shows multiple attempts to run app, which sometimes have smaller width < 1000px, but sometimes uses proper 2000px width from `preferred-width` property

https://github.com/slint-ui/slint/assets/41945903/5071931f-8fc0-48e0-ab36-3d4e8456ce31

**Comment by tronical** [comment]
Do I see correctly that this is under Gnome? Do you know if it's using Wayland or X11?

**Comment by qarmin** [comment]
I run this under gnome - Ubuntu 23.04 X11

Now I reinstalled OS and installed Ubuntu 23.10 with same hardware and problem still happens


https://github.com/slint-ui/slint/assets/41945903/b3b651ed-975a-43b3-8261-ce2506645ef5

`inxi -GS -x`
```
System:
  Host: rafal-komputer Kernel: 6.5.0-10-generic arch: x86_64 bits: 64
    compiler: N/A Desktop: GNOME v: 45.0 Distro: Ubuntu 23.10 (Mantic Minotaur)
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: Sapphire driver: amdgpu v: kernel arch: GCN-4 bus-ID: 01:00.0
    temp: 49.0 C
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 23.2.0 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
    gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.2.1-1ubuntu3 renderer: AMD Radeon RX 570
    Series (polaris10 LLVM 15.0.7 DRM 3.54 6.5.0-10-generic)
    direct-render: Yes
```
