### ISSUE TITLE
compiler panic in move_declarations.rs

### ISSUE THREAD

**Issue by stolen-programmer** [slint-ui/slint#3916]
```slint
import {StandardTableView} from "std-widgets.slint";

export component Window {
    VerticalLayout {

        filter := TextInput {
            height: 20px;
        }

        v := StandardTableView {
            // width: 230px;
            // height: 200px;
            columns: [
                { title: "Header 1" },
                { title: "Header 2" },
            ];
            rows: [
                [
                    { text: "Item 1" }, { text: "Item 2" },
                ],
                [
                    { text: "Item 1" }, { text: "Item 2" },
                ],
                [
                    { text: "Item 1" }, { text: "Item 2" },
                ]
            ];
        }

    }
    

}
```

Starting preview crashes when the component name is Window

Cargo.toml

```toml
[package]
name = "manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tokio]
version = "1.34.0"
features = ["full"]

[dependencies.slint]
version = "1.2.2"

[dependencies.reqwest]
version = "0.11.22"

[build-dependencies]
slint-build = "1.2.2"

```

```shell
$ cargo --version
cargo 1.73.0 (9c4383fb5 2023-08-26)
$ rustc --version
rustc 1.73.0 (cc66ad468 2023-10-03)
```

Host x86_64 Windows 10

vscode slint plugin
