### ISSUE TITLE
Artifacts when resizing window

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#3990]
Slint 1.3.0 Femtovg(and also skia)

https://github.com/slint-ui/slint/assets/41945903/0fe4f9f5-1643-4a1d-adf9-7305f1cedfe5

Software renderer

https://github.com/slint-ui/slint/assets/41945903/317cb2d1-fcc0-43f1-89bf-7b0829855216

Czkawka (GTK 4.12.3)

https://github.com/slint-ui/slint/assets/41945903/a95e57f0-5a3f-4628-ba1a-d2099f892cca

**Comment by tronical** [comment]
I can't reproduce this :( I tried with various Slint examples on macOS, Windows, X11, and Wayland (under Gnome), with an i915 and a Radio 5500M. Could you describe your system setup a little? What kind of graphics card and driver are you using on Linux?

**Comment by qarmin** [comment]
```
System:
  Host: rafal-komputer Kernel: 6.5.0-14-generic arch: x86_64 bits: 64
    Desktop: GNOME v: 45.1 Distro: Ubuntu 23.10 (Mantic Minotaur)
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 23.2.0 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
    gpu: amdgpu resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.2.1-1ubuntu3.1 renderer: AMD Radeon RX 570
    Series (polaris10 LLVM 15.0.7 DRM 3.54 6.5.0-14-generic)
```
apt reports mesa version `23.2.1-1ubuntu3.1` - all graphics components comes directly from official ubuntu repositories.

I'm using X11(not sure why Xwayland is printed in output) on RX 570
