### ISSUE TITLE
Prepare initial documentation for application deployment for Rust, C++, and Node.js

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#4408]
In each of the language specific docs, we should have a chapter that explains what language specific (and non-language specific) steps need to be taken to prepare the application for deployment. Each chapter can be divided into target operating systems.

Examples of language-specific steps are console subsystem de-selection Windows (see also #3235).

**Comment by anshap1719** [comment]
Hi @NigelBreslaw, has there been any progress on this?

**Comment by NigelBreslaw** [comment]
@anshap1719 what platform were you specifically looking for more info on?

**Comment by anshap1719** [comment]
@NigelBreslaw Sorry, should've mentioned. I'm looking for MacOS at the moment to prepare an app for Apple App Store submission.

**Comment by NigelBreslaw** [comment]
@anshap1719 Okay the short answer is 'no this hasn't progressed'. However I'm happy to work with you to get this sorted out! The main thing on my mind is we need to sort out generating a working Xcode project. I've got a hobby project where I managed to get a .pkg and then "manually" did the work to get the correct info.plist, certificates, add entitlements and the multiple signing steps to get it all correctly signed and notarised. Otherwise TestFlight and the App Store can't be used. It's a nightmare, Apple often change the way these things work and there is no way we can support all those steps. 

However if we have an actual Xcode project then things become much simpler. I can start to have a look tomorrow. Have you tried anything yourself so far? Also feel free to drop by our Mattermost chat instance if that speeds up the communication. chat.slint.dev

**Comment by anshap1719** [comment]
@NigelBreslaw I haven't tried anything yet, but I'd probably look into how tauri does it and try if similar methods work with Slint as well. Also, I have no experience with Xcode and its build files, so I'm unsure how helpful I can be, however, I'll do my best to assist wherever possible.

**Comment by anshap1719** [comment]
@NigelBreslaw I just came across this: https://github.com/crabnebula-dev/cargo-packager

Looks like it has everything needed to package the app properly, I'm going to test it out this weekend.

**Comment by anshap1719** [comment]
@NigelBreslaw Ok, so that was relatively easy. I was able to 
1. Build a universal binary (using lipo)
2. Create the signed `.app` bundle with the correct plist files, resources, icons, code signature etc 
3. Create a signed `.pkg` file
4. Upload it to app store connect and make it available to myself via TestFlight
5. Install it via TestFlight
6. Run the app

Everything went smoothly.

**Comment by anshap1719** [comment]
Since none of the steps complained, I don't believe there will be any issue when submitting the app in terms of signing or configuration or resource files. Because otherwise, either TestFlight or `altool` complains.

**Comment by anshap1719** [comment]
I also learned that `tauri` is basically a part of `crabnebula`, and their tooling has a huge overlap. So this packager toolkit is also what tauri uses internally it seems.

**Comment by NigelBreslaw** [comment]
OH wow! Thank you so much for taking the time to work this out. I will go through the steps myself and then add them to the documentation.

**Comment by anshap1719** [comment]
@NigelBreslaw Great! I'll just add the config I used here for reference:

```toml
# Packager.toml

name = "dummy"
product-name = "Dummy App"
identifier = "com.app.dummy"
version = "0.1.0"
out-dir = "./dist"
binaries = [{ main = true, path = "dummy" }] # Must match Rust bin name
before-packaging-command = "./build.sh"
formats = ["app"]
icons = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
]
category = "Photography"

[macos]
entitlements = "./Entitlements.plist"
info-plist-path = "./Info.plist"
signing-identity = "<identity>"
embedded-provisionprofile-path = "$HOME/dummy.provisionprofile"
# Universal binary is required for supporting this
minimum-system-version = "10.13"
```

```sh
# build.sh

#!/usr/bin/env bash

set -eou pipefail

cargo build --release --target aarch64-apple-darwin
cargo build --release --target x86_64-apple-darwin

mkdir -p ./target/universal-apple-darwin/release/

lipo -create -output ./target/universal-apple-darwin/release/dummy ./target/aarch64-apple-darwin/release/dummy ./target/x86_64-apple-darwin/release/dummy

cp ./target/universal-apple-darwin/release/dummy ./dist/dummy
```

```sh
# signed-build.sh

#!/usr/bin/env bash

set -eou pipefail

cargo packager --release
xcrun productbuild --sign "<certificate name>" --component "./dist/dummy.app" /Applications "dummy.pkg"
```

I was then able to push the `.pkg` to app store connect.

I haven't tried any other platforms, but MacOS generally seems to be the hardest one, so it should work on others too.
