### ISSUE TITLE
in the Init function, ScrollView to the bottom, panicked Recursion detected

### ISSUE THREAD

**Issue by Aileyugg** [slint-ui/slint#4522]
```css
Rectangle {
        background: #fff9;
        border-radius: 6px;
        scroll-view := ScrollView {
            protected function to-bottom() {
                self.viewport-y = self.visible-height - self.viewport-height;
            }

            VerticalLayout {
                alignment: start;
                padding: 8px;
                for i in root.message-data: Text {
                    text: i.text;
                    wrap: word-wrap;
                    init => {
                        debug("first");
                        to-bottom();
                    }
                }
            }
}
```

first
thread 'main' panicked at C:\Users\xx\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\i-slint-core-1.4.0\properties.rs:486:9:
Recursion detected
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
