### ISSUE TITLE
Windows11x64 use vulkan failed

### ISSUE THREAD

**Issue by JiuXin303** [slint-ui/slint#5360]
I used the official template and only added the features option for Vulkan in the Cargo.toml file.

```toml
[dependencies]
slint = { version = "1.6", features = ["renderer-skia-vulkan"] }

[build-dependencies]
slint-build = "1.6"
```

The following is a screenshot of my program reporting an error:
<img width="859" alt="image" src="https://github.com/slint-ui/slint/assets/50227375/7c6e143f-7755-4939-bb88-c3fac78980ae">

I can't find any examples of using Vulkan except for the documentation, and I don't know how to use it.
Can you add an example to the project?
