### ISSUE TITLE
Window property always-on-top does not work on linux

### ISSUE THREAD

**Issue by michaelrampl** [slint-ui/slint#6691]
On Linux (nixos) both under x11 and wayland (tested using KDE), the `always-on-top` property doesn't seem to work

Cargo.toml
```toml
[package]
name = "rec_flow"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
```

main.slint
```slint
import { Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    always-on-top: true;
}

```

main.rs
```rs
slint::include_modules!();
fn main() {
    MainWindow::new().unwrap().run().unwrap();
}

```

It looks like SLINT uses the `winit` crate which should support the feature tough https://docs.rs/winit/latest/winit/window/enum.WindowLevel.html#variant.AlwaysOnTop
